apiVersion: apps/v1
kind: Deployment
metadata:
  name: depi-ddeploy
spec:
  replicas: 3
  selectors:
    matchLabels:
        env: prod
  template:
    metadata:
      name: pod-depii
      labels:
        env: prod
    spec:
      containers:
        - name: depi-containers
          image:  enabdelhamed/depi-front:v1
          
  